# Generated by Django 5.1.3 on 2024-11-13 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="group",
            old_name="created_by",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="grouping",
            old_name="created_by",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="plan",
            old_name="created_by",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="scaledrecipe",
            old_name="created_by",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="shoppinglist",
            old_name="created_by",
            new_name="user",
        ),
    ]
