# Generated by Django 5.1.3 on 2024-11-13 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0002_rename_created_by_group_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-saved_at"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="grouping",
            name="unique_template_name",
        ),
        migrations.AddConstraint(
            model_name="grouping",
            constraint=models.UniqueConstraint(
                condition=models.Q(("plan__isnull", True)),
                fields=("name", "user"),
                name="unique_template_name",
            ),
        ),
        migrations.AddField(
            model_name="savedrecipe",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="planner.recipe"
            ),
        ),
        migrations.AddField(
            model_name="savedrecipe",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="saved_by",
            field=models.ManyToManyField(
                related_name="saved_recipes",
                through="planner.SavedRecipe",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="savedrecipe",
            unique_together={("user", "recipe")},
        ),
    ]
