# Generated by Django 5.1.3 on 2024-11-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0002_recreate_dropped_tables"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppingitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("fruit_veg", "Fruit & Vegetables"),
                    ("meat_fish", "Meat & Fish"),
                    ("dairy", "Dairy & Deli"),
                    ("bakery", "Bakery"),
                    ("pantry", "Pantry"),
                    ("drinks", "Drinks"),
                    ("snacks", "Snacks"),
                    ("frozen", "Frozen"),
                    ("non_food", "Non-food"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterModelOptions(
            name="shoppingitem",
            options={"ordering": ["category", "item"]},
        ),
        migrations.DeleteModel(
            name="ShoppingCategory",
        ),
    ]
