# Generated by Django 5.1.3 on 2024-11-29 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0003_alter_shoppingitem_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="template",
            name="user",
        ),
        migrations.RemoveField(
            model_name="mealplan",
            name="template",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="ingredients_digest",
        ),
        migrations.RemoveField(
            model_name="shoppinglist",
            name="content_digest",
        ),
        migrations.CreateModel(
            name="GroupRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField()),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipes",
                        to="planner.group",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="planner.recipe"
                    ),
                ),
            ],
            options={
                "ordering": ["group", "order"],
                "unique_together": {("order",)},
            },
        ),
        migrations.DeleteModel(
            name="ScaledRecipe",
        ),
        migrations.DeleteModel(
            name="Template",
        ),
    ]
