# Generated by Django 5.1.3 on 2024-11-29 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0004_remove_template_user_remove_mealplan_template_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppingitem",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RenameModel(
            old_name="Group",
            new_name="MealGroup",
        ),
        migrations.CreateModel(
            name="MealGroupRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField()),
                (
                    "meal_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipes",
                        to="planner.mealgroup",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="planner.recipe"
                    ),
                ),
            ],
            options={
                "ordering": ["meal_group", "order"],
                "unique_together": {("order",)},
            },
        ),
        migrations.DeleteModel(
            name="GroupRecipe",
        ),
    ]
