# Generated by Django 5.1.3 on 2024-11-29 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0005_shoppingitem_modified_at_rename_group_mealgroup_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MealGroupRecipe",
            new_name="MealPlanRecipe",
        ),
    ]
