# Generated by Django 5.1.3 on 2024-11-30 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0006_rename_mealgrouprecipe_mealplanrecipe"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="mealplanrecipe",
            unique_together={("meal_group", "order")},
        ),
    ]
