# Generated by Django 5.1.3 on 2024-12-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0008_alter_mealplanrecipe_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealplan",
            name="last_viewed_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
