# Generated by Django 5.1.3 on 2024-12-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0009_mealplan_last_viewed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppingitem",
            name="item",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="shoppingitem",
            name="quantity",
            field=models.CharField(max_length=20),
        ),
    ]
