# Generated by Django 5.1.3 on 2024-12-14 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0010_alter_shoppingitem_item_alter_shoppingitem_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shoppinglist",
            name="meal_plan",
        ),
    ]
