# Generated by Django 5.1.3 on 2024-12-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0011_remove_shoppinglist_meal_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppingitem",
            name="notes",
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
