# Generated by Django 5.1.3 on 2024-12-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0013_shoppinglist_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppinglist",
            name="last_viewed_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
