# Generated by Django 5.1.3 on 2024-12-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0014_shoppinglist_last_viewed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppinglist",
            name="name",
            field=models.CharField(default="Shopping List", max_length=40),
        ),
    ]
