# Generated by Django 5.1.3 on 2024-12-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0015_alter_shoppinglist_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppingitem",
            name="quantity",
            field=models.CharField(max_length=100),
        ),
    ]
