# Generated by Django 5.1.3 on 2024-12-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0018_alter_shoppingitem_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shoppingitem",
            name="notes",
        ),
        migrations.AddField(
            model_name="shoppingitem",
            name="used_in",
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
