# Generated by Django 5.1.3 on 2024-12-14 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0019_remove_shoppingitem_notes_shoppingitem_used_in"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shoppingitem",
            name="used_in",
        ),
        migrations.AddField(
            model_name="shoppingitem",
            name="recipe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="planner.recipe",
            ),
        ),
    ]
