# Generated by Django 5.1.3 on 2024-12-15 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0020_remove_shoppingitem_used_in_shoppingitem_recipe"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shoppingitem",
            options={"ordering": ["category", "name"]},
        ),
        migrations.RenameField(
            model_name="shoppingitem",
            old_name="item",
            new_name="name",
        ),
    ]
