# Generated by Django 5.1.3 on 2024-12-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0021_alter_shoppingitem_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="instructionstep",
            old_name="step",
            new_name="text",
        ),
        migrations.AlterField(
            model_name="shoppingitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("fruit_veg", "Fruit & Vegetables"),
                    ("meat_fish", "Meat & Fish"),
                    ("dairy", "Dairy & Deli"),
                    ("bakery", "Bakery"),
                    ("pantry", "Pantry"),
                    ("snacks", "Snacks"),
                    ("frozen", "Frozen"),
                    ("drinks", "Drinks"),
                    ("non_food", "Non-food"),
                ],
                max_length=20,
            ),
        ),
    ]
