# Generated by Django 5.1.3 on 2024-12-15 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0022_rename_step_instructionstep_text_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingredient",
            old_name="item",
            new_name="name",
        ),
    ]
