# Generated by Django 5.1.3 on 2024-12-16 08:59

import planner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0025_recipe_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                blank=True,
                default="img/recipe_placeholder.png",
                upload_to=planner.models.recipe_image_path,
            ),
        ),
    ]
