# Generated by Django 5.1.3 on 2024-12-16 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0030_alter_recipe_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="image",
        ),
    ]
