# Generated by Django 5.1.3 on 2025-01-12 14:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0033_rename_profile_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="uuid",
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
