# Generated by Django 5.1.3 on 2025-01-12 14:19

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    Recipe = apps.get_model('planner', 'Recipe')
    for row in Recipe.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0034_recipe_uuid"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
