# Generated by Django 5.1.3 on 2025-01-17 21:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0036_alter_recipe_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealplan",
            name="uuid",
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name="shoppinglist",
            name="uuid",
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
