# Generated by Django 5.1.3 on 2025-01-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0038_populate_meal_plan_and_shopping_list_uuids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mealplan",
            name="uuid",
            field=models.UUIDField(blank=True, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="shoppinglist",
            name="uuid",
            field=models.UUIDField(blank=True, editable=False, unique=True),
        ),
    ]
